import type { Locale } from "./locale";
export const SITE_COPY = {
  tr: {
    instagramAuthNotice: "Instagram içinden açtıysan, kayıt veya giriş yapmadan önce menüden bu sayfayı Safari ya da Chrome’da açmanı öneririz. E-postandaki koda bakmak için uygulama değiştirdiğinde Instagram kayıt ekranını kapatabilir. Tarayıcı değiştirdikten sonra doğrulama işlemini yeniden başlatman gerekebilir.",
    cookieSettings: "Çerez ayarları",
    cookieNotice: "Google Analytics ile ziyaretleri ve tamamlanan kayıtları ölçmek için yalnızca izninle analiz çerezleri kullanıyoruz. Reddetmek hizmeti etkilemez. İznini çerez ayarlarından geri çekebilirsin.",
    cookieAccept: "Kabul et",
    cookieDecline: "Reddet",

    signIn: "Giriş yap", signUp: "Kayıt ol", account: "Hesabım", theme: "Tema değiştir",
    footer: "Almanya’dan her sabah, Türkçe, İngilizce ve Almanca özet.",
    choose: "Hangi kategorilerin özetini görmek istediğini seç.", favorites: "Favori kategoriler",
    history: "Geçmiş özetler", empty: "Henüz gösterilecek bir özet yok.",
    preferences: "Seçtiğin kategoriler, sana gönderilen günlük e-postayı ve aşağıdaki geçmiş özet listesini filtreler — ana sayfadaki günlük dijest herkese aynı şekilde gösterilir. Hiçbirini seçmezsen tüm kategorileri alırsın.",
    freeLimit: "Ücretsiz planda en fazla 1 kategori seçebilirsin.",
    save: "Kaydet", saving: "Kaydediliyor...", saved: "Kaydedildi — bir sonraki e-postandan itibaren geçerli olacak.", error: "Bir şeyler ters gitti.",
    pro: "Pro üye", free: "Ücretsiz plan", proDescription: "Tüm kategoriler ve istediğin saatte teslimat açık.",
    manage: "Üyeliğimi yönet", upgrade: "Pro’ya yükselt",
    description: "Almanya’daki en önemli haberlerin günlük Türkçe özeti.",
    privacyLink: "Gizlilik Politikası", emailLanguage: "Günlük e-posta dili",
    premiumComingSoon: "Genişletilmiş premium sürüm üzerinde çalışıyoruz.",
  },
  de: {
    instagramAuthNotice: "Wenn du diese Seite in Instagram geöffnet hast, öffne sie vor der Registrierung oder Anmeldung über das Browsermenü in Safari oder Chrome. Beim Wechsel zur E-Mail-App kann Instagram den Registrierungsbildschirm schließen. Nach dem Browserwechsel musst du die Verifizierung möglicherweise neu starten.",
    cookieSettings: "Cookie-Einstellungen",
    cookieNotice: "Mit deiner Einwilligung verwenden wir Google-Analytics-Cookies, um Besuche und abgeschlossene Registrierungen zu messen. Ablehnen beeinträchtigt den Dienst nicht. Du kannst deine Einwilligung in den Cookie-Einstellungen widerrufen.",
    cookieAccept: "Akzeptieren",
    cookieDecline: "Ablehnen",

    signIn: "Anmelden", signUp: "Registrieren", account: "Mein Konto", theme: "Farbschema wechseln",
    footer: "Nachrichten aus Deutschland, jeden Morgen auf Türkisch, Englisch und Deutsch zusammengefasst.",
    choose: "Wähle die Kategorien, denen du folgen möchtest.", favorites: "Lieblingskategorien",
    history: "Frühere Ausgaben", empty: "Noch keine Zusammenfassungen vorhanden.",
    preferences: "Deine Kategorien filtern die tägliche E-Mail und die früheren Ausgaben unten. Auf der Startseite sehen alle dieselbe Ausgabe. Wenn du keine Kategorie auswählst, erhältst du alle Kategorien.",
    freeLimit: "Im kostenlosen Tarif kannst du höchstens 1 Kategorie auswählen.",
    save: "Speichern", saving: "Wird gespeichert…", saved: "Gespeichert — gilt ab deiner nächsten E-Mail.", error: "Etwas ist schiefgelaufen.",
    pro: "Pro-Mitglied", free: "Kostenloser Tarif", proDescription: "Alle Kategorien und Zustellung zu deiner Wunschzeit.",
    manage: "Abonnement verwalten", upgrade: "Auf Pro upgraden",
    description: "Die wichtigsten Nachrichten aus Deutschland, täglich zusammengefasst.",
    privacyLink: "Datenschutzerklärung", emailLanguage: "Sprache der täglichen E-Mail",
    premiumComingSoon: "Wir arbeiten an einer erweiterten Premium-Ausgabe.",
  },
  en: {
    instagramAuthNotice: "If you opened this page in Instagram, we recommend opening it in Safari or Chrome from the browser menu before signing up or signing in. Switching apps to read your email code may close Instagram’s registration screen. You may need to restart verification after switching browsers.",
    cookieSettings: "Cookie settings",
    cookieNotice: "With your permission, we use Google Analytics cookies to measure visits and completed registrations. Declining does not affect the service. You can withdraw consent in cookie settings.",
    cookieAccept: "Accept",
    cookieDecline: "Decline",

    signIn: "Sign in", signUp: "Sign up", account: "My Account", theme: "Toggle theme",
    footer: "German news every morning, summarized in Turkish, English and German.",
    choose: "Choose the categories you want to follow.", favorites: "Favorite categories",
    history: "Past digests", empty: "No digests to show yet.",
    preferences: "Your categories filter your daily email and the digest history below. Everyone sees the same daily digest on the homepage. Leave all categories unselected to receive every category.",
    freeLimit: "The Free plan allows up to 1 favorite category.",
    save: "Save", saving: "Saving...", saved: "Saved — applies from your next email.", error: "Something went wrong.",
    pro: "Pro member", free: "Free plan", proDescription: "All categories and your choice of delivery time.",
    manage: "Manage subscription", upgrade: "Upgrade to Pro",
    description: "A daily summary of the most important German news in English.",
    privacyLink: "Privacy Policy", emailLanguage: "Daily email language",
    premiumComingSoon: "We're working on an expanded premium edition.",
  },
} satisfies Record<Locale, Record<string, string>>;
